Update treq
twisted/klein pull request #401
Opened 2020-09-15 20:48 UTC by wsanchez

Update treq, which is necessary to address [build failures against Twisted trunk](https://travis-ci.org/github/twisted/klein/jobs/727451550).

2020-09-15 20:55 UTC, wsanchez commented
The latest release of `treq` causes build failures due to use of `twisted.python.compat._PY3`, so this uses the current latest commit on master.

That still fails due to #339.

2020-09-15 21:00 UTC, wsanchez commented
https://github.com/twisted/treq/issues/293 requests a Treq release.

2020-12-19 11:35 UTC, adiroiban requested changes
Does this draft require a review?

I am just trying to clean my https://github.com/pulls/review-requested queue  :)

2020-12-20 03:14 UTC, twm commented
@adiroiban I believe that it needs to be changed to reference treq 20.9.0 first.

2020-12-21 22:09 UTC, wsanchez commented
@twm updated, but we still have #339.

Our options here are (a) fix treq to do what @glyph thinks is correct regarding `+` (which presumably means fixing https://github.com/python-hyper/hyperlink/issues/129) or (b) changing `test_form.py` to stop caring what @glyph thinks, or (c) stop using `treq` in our test suite.

2020-12-21 23:18 UTC, twm commented
@wsanchez I think that the ideal outcome is to fix Hyperlink. Its current behavior is to corrupt a common sequence in the most common type of URL. I definitely wouldn't have made treq pass all URLs through it if I'd known of that behavior, and it makes Hyperlink totally unsuited for use on the server side, as in [Twisted #9359](https://twistedmatrix.com/trac/ticket/9359). It seems like a two birds with one stone situation to me.

As a fallback, I could make treq avoid using Hyperlink, which has also caused other problems (treq#303). That would fix it in this Klein case, but not help https://github.com/twisted/twisted/pull/970.

2020-12-21 23:31 UTC, wsanchez commented
@twm agreed. Like Klein, Hyperlink lacks active developers who will review code, so… if you submit a PR, I can review and merge, then cajole Mahmoud to make a release.

2020-12-21 23:57 UTC, glyph commented
I'd really like to get it fixed & released in Hyperlink. I'm on vacation (let me pause just a moment to take a sip out of my [mug](https://twitter.com/glyph/status/1340793364795420673?s=20) here) so I might have a *few* spare cycles to help get this over the line in the next couple of weeks.  I am working a couple of days, and I am planning to spend the rest of it playing World of Warcraft, but I will try to have a few minutes between raids.

2020-12-23 07:09 UTC, twm commented
I gave fixing it in treq a shot. Unfortunately even the raw `hyperlink.URL` still mangles in this way. I'd have to back out treq's internal use of Hyperlink entirely to avoid this issue. [This PR](https://github.com/twisted/treq/pull/304) has a test to reproduce.

Meanwhile, both Hyperlink and treq are having CI issues. Hyperlink's issue is Travis (I guess builds pass... eventually?) and treq's is... several things, including Travis and OpenSSL. I filed some PRs:

* https://github.com/twisted/treq/pull/308 (this is in code-coverage-tool hell)
* https://github.com/python-hyper/hyperlink/pull/142 (this isn't working at all, and I've no idea why; perhaps because I don't have write on the repo?)

There are several other treq PRs that need to go in before release, all small. I've started poking at a real fix in Hyperlink, but no promises there.

2020-12-28 08:26 UTC, glyph commented
@twm Welp, right at the end of vacation, I did manage to squeeze this in: https://github.com/python-hyper/hyperlink/pull/145

2020-12-29 20:20 UTC, twm commented
@glyph I submitted https://github.com/python-hyper/hyperlink/pull/146 to your PR, which also fixes the issue for `hyperlink.URL`.

2020-12-30 05:43 UTC, glyph commented
@wsanchez @twm would one of you mind updating this PR to bump the `hyperlink` pin to point at trunk, just to get CI passing?  We'll probably still want to put it on hold

2020-12-30 06:28 UTC, twm commented
It seems like the build timeouts may be too short?

2020-12-30 07:41 UTC, glyph commented
> It seems like the build timeouts may be too short?

It shouldn't take 30 minutes to run the unit tests. I think the problem is something broken with the usage of Hypothesis?  I get errors locally about it generating too many tests.  (I think that Klein is probably the wrong layer for most of these Hypothesis tests anyway; *mostly* they're testing HTTP parsing and URL stuff that should be handled by Hyperlink, Twisted, or Hyper H2, I think).

2021-01-11 18:46 UTC, wsanchez commented
> (I think that Klein is probably the wrong layer for most of these Hypothesis tests anyway; _mostly_ they're testing HTTP parsing and URL stuff that should be handled by Hyperlink, Twisted, or Hyper H2, I think).

These are moving to Hyperlink, but we do *use* the strategies, so I need to dig into why sometimes they stall out, but that fix will end up being in Hyperlink.

2021-01-11 18:47 UTC, wsanchez commented
OK I've updated Hyperlink and that seems to work without an update to Treq, which we can update out of band from this PR when it releases.

2021-01-12 15:39 UTC, adiroiban approved these changes
All good. Thanks.

A minor comment.

Reduce the name "Unit test with Python on Ubuntu with Twisted current" is it make is harder to see the duration from one go:

![image](https://user-images.githubusercontent.com/204609/104336324-313c9100-54ec-11eb-8aa1-66e81942b4da.png)

2021-01-12 21:01 UTC, merged

2021-01-12 21:07 UTC, glyph commented
🎉